const $=id=>document.getElementById(id);
const CHARS=[{n:'Pahlawan Keris',s:'⚔️'},{n:'Puteri Arkib',s:'📜'},{n:'Penjelajah Masa',s:'⏳'}];
let profile=JSON.parse(localStorage.getItem('sejarahProfile')||'null')||{name:'',char:0,unlocked:1,badges:[]};
profile.badges=profile.badges||[];
let selectedChar=profile.char||0,world=0,questions=[],index=0,enemyHp=100,score=0,combo=0,hints=3,locked=false,errors=[],timeLeft=20,timer=null,advanceTimer=null,selected=[],essaySelected=[];
function setView(id){['home','game','builder','essay','result'].forEach(x=>$(x).classList.add('hide'));$(id).classList.remove('hide')}
function sync(){$('playerTop').textContent=profile.name||'-';$('scoreTop').textContent=score;$('comboTop').textContent=combo;$('hintTop').textContent=hints;$('timerTop').textContent=timeLeft;$('timerPill').classList.toggle('timerLow',timeLeft<=5);$('hintBtn').disabled=hints<=0}
$('characters').innerHTML=CHARS.map((c,i)=>`<button class="character ${i===selectedChar?'selected':''}" onclick="selectChar(${i})"><div class="avatar">${c.s}</div><h3>${c.n}</h3></button>`).join('');
$('studentName').value=profile.name||'';
function selectChar(i){selectedChar=i;document.querySelectorAll('.character').forEach((e,n)=>e.classList.toggle('selected',n===i))}
function saveProfile(){profile={...profile,name:$('studentName').value.trim()||'Pelajar',char:selectedChar,unlocked:profile.unlocked||1};localStorage.setItem('sejarahProfile',JSON.stringify(profile));renderMap();$('map').classList.remove('hide');$('saved').classList.add('hide');sync()}
function renderMap(){const h=JSON.parse(localStorage.getItem('sejarahHistory')||'[]');$('worlds').innerHTML=NAMES.map((n,i)=>{const open=i<profile.unlocked;return `<div class="world ${open?'open':'locked'}"><small>WORLD ${i+1}</small><h3>${n}</h3><p>${open?(i<DATA.length?'已开放':'即将制作'):'完成前一世界后解锁'}</p>${open&&i<DATA.length?`<button onclick="startGame(${i})">进入 World ${i+1}</button>`:''}</div>`}).join('');$('badges').innerHTML=profile.badges.length?profile.badges.map(x=>`<div class="badge"><strong>${x}</strong></div>`).join(''):'<p>完成 World 后获得徽章。</p>';$('revisionRoute').innerHTML=h.length?h.slice(-6).reverse().map(x=>`<div class="route"><strong>World ${x.world}</strong><p>正确率 ${x.accuracy}%</p><button onclick="startGame(${x.world-1})">重新挑战</button></div>`).join(''):'<p>完成 World 后自动生成复习路线。</p>'}
function showSaved(){$('map').classList.add('hide');$('saved').classList.remove('hide');const h=JSON.parse(localStorage.getItem('sejarahHistory')||'[]');$('saved').innerHTML='<h2>教师成绩面板</h2>'+(h.length?h.slice().reverse().map(x=>`<div class="reviewItem"><b>${x.name}</b>｜World ${x.world}｜${x.score}分｜${x.accuracy}%｜错题 ${x.errors}</div>`).join(''):'<p>尚无成绩。</p>')}
function startGame(w){clearInterval(timer);clearTimeout(advanceTimer);world=w;questions=DATA[w].qs;index=0;enemyHp=100;score=0;combo=0;hints=3;errors=[];$('heroSprite').textContent=CHARS[profile.char||0].s;$('heroName').textContent=profile.name||'Pelajar';$('enemySprite').textContent=DATA[w].icon;$('enemyName').textContent=DATA[w].enemy;$('hpBar').style.width='100%';$('hpText').textContent='HP 100 / 100';setView('game');renderQuestion()}
function renderQuestion(){clearInterval(timer);clearTimeout(advanceTimer);locked=false;$('nextBtn').classList.add('hide');$('feedback').className='card hide';const x=questions[index];$('meta').textContent=`WORLD ${world+1} • SOALAN ${index+1}/${questions.length}`;$('question').textContent=x.q;$('answers').innerHTML=x.a.map((v,n)=>`<button class="answer" data-n="${n}" onclick="pick(${n},this)">${String.fromCharCode(65+n)}. ${v}</button>`).join('');$('taunt').textContent=index>=questions.length/2?'你真的追得上我的分数吗？':'历史不是背诵，是战斗。';timeLeft=20;sync();timer=setInterval(()=>{timeLeft--;sync();if(timeLeft<=0){clearInterval(timer);handleTimeout()}},1000)}
function lockAnswers(){document.querySelectorAll('.answer').forEach(b=>b.disabled=true)}
function pick(n,btn){if(locked)return;locked=true;clearInterval(timer);const x=questions[index],buttons=[...document.querySelectorAll('.answer')];lockAnswers();buttons[x.c].classList.add('ok');if(n===x.c){combo++;score+=100+combo*20;enemyHp=Math.max(0,enemyHp-Math.ceil(100/questions.length));$('heroSprite').classList.add('attack');$('enemySprite').classList.add('hit');$('feedback').className='card correctBox';$('feedback').innerHTML=`<b>正确！</b><br>Combo × ${combo}<br><b>关键词：</b>${x.kw}`}else{combo=0;btn.classList.add('bad');errors.push({...x,chosen:n});$('feedback').className='card wrongBox';$('feedback').innerHTML=`<b>需要订正</b><br><b>华语解释：</b>${x.cn}<br><b>正确答案：</b>${x.a[x.c]}<br><b>关键词：</b>${x.kw}`}$('feedback').classList.remove('hide');$('hpBar').style.width=enemyHp+'%';$('hpText').textContent=`HP ${enemyHp} / 100`;$('nextBtn').classList.remove('hide');sync();setTimeout(()=>{$('heroSprite').classList.remove('attack');$('enemySprite').classList.remove('hit')},500);advanceTimer=setTimeout(nextQuestion,2200)}
function handleTimeout(){if(locked)return;locked=true;const x=questions[index],buttons=[...document.querySelectorAll('.answer')];lockAnswers();buttons[x.c].classList.add('ok');combo=0;errors.push({...x,chosen:-1});$('feedback').className='card wrongBox';$('feedback').innerHTML=`<b>时间到</b><br><b>正确答案：</b>${x.a[x.c]}<br><b>华语解释：</b>${x.cn}<br><b>关键词：</b>${x.kw}`;$('feedback').classList.remove('hide');$('nextBtn').classList.remove('hide');advanceTimer=setTimeout(nextQuestion,2200)}
function nextQuestion(){if(!locked)return;clearTimeout(advanceTimer);index++;index>=questions.length?startBuilder():renderQuestion()}
function useHint(){if(locked||hints<=0)return;hints--;const x=questions[index],wrong=[0,1,2,3].filter(n=>n!==x.c).sort(()=>Math.random()-.5).slice(0,2);wrong.forEach(n=>{const b=document.querySelector(`[data-n="${n}"]`);if(b)b.disabled=true});$('feedback').className='card';$('feedback').innerHTML='<b>神秘人出现：</b>已排除两个错误答案。';$('feedback').classList.remove('hide');sync()}
function startBuilder(){clearInterval(timer);setView('builder');selected=[];$('builderTitle').textContent=`World ${world+1} Struktur Challenge`;$('builderQuestion').textContent=DATA[world].bq;$('builderFeedback').className='card hide';renderBuilder()}
function renderBuilder(){$('slots').innerHTML=[0,1].map(i=>`<div class="builderSlot">${selected[i]||`Isi ${i+1}：点击答案`}</div>`).join('');const wrong=['Jawapan ini tidak berkaitan dengan soalan.','Fakta ini bercanggah dengan kandungan bab.'];$('builderOptions').innerHTML=[...DATA[world].ba,...wrong].map(v=>`<button class="builderOption" onclick='chooseBuilder(${JSON.stringify(v)})'>${v}</button>`).join('')}
function chooseBuilder(v){if(!selected.includes(v)&&selected.length<2){selected.push(v);renderBuilder()}}
function checkBuilder(){const ok=DATA[world].ba.every(v=>selected.includes(v));if(ok){score+=400;$('builderFeedback').className='card correctBox';$('builderFeedback').innerHTML='<b>Struktur：4/4 分</b>';setTimeout(startEssay,900)}else{$('builderFeedback').className='card wrongBox';$('builderFeedback').innerHTML='<b>答案不完整，请重新选择。</b>';selected=[];renderBuilder()}$('builderFeedback').classList.remove('hide');sync()}
function startEssay(){setView('essay');essaySelected=[];$('essayTitle').textContent=`World ${world+1} Esei Challenge`;$('essayQuestion').textContent=DATA[world].eq;$('essayFeedback').className='card hide';renderEssay()}
function renderEssay(){$('essaySlots').innerHTML=['Isi 1','Huraian','Isi 2','Penegasan'].map((x,i)=>`<div class="builderSlot"><b>${x}</b><br>${essaySelected[i]||'尚未选择'}</div>`).join('');const wrong=['Jawapan ini tidak menjawab kehendak soalan.','Fakta ini terlalu umum.'];$('essayOptions').innerHTML=[...DATA[world].ea,...wrong].map(v=>`<button class="essayCard ${essaySelected.includes(v)?'selected':''}" onclick='chooseEssay(${JSON.stringify(v)})'>${v}</button>`).join('')}
function chooseEssay(v){if(!essaySelected.includes(v)&&essaySelected.length<4){essaySelected.push(v);renderEssay()}}
function checkEssay(){const ok=DATA[world].ea.every(v=>essaySelected.includes(v));if(ok){score+=800;$('essayFeedback').className='card correctBox';$('essayFeedback').innerHTML='<b>Esei：8/8 分</b>';setTimeout(showResult,1000)}else{$('essayFeedback').className='card wrongBox';$('essayFeedback').innerHTML='<b>Esei belum lengkap.</b>';essaySelected=[];renderEssay()}$('essayFeedback').classList.remove('hide');sync()}
function showResult(){setView('result');const correct=questions.length-errors.length,accuracy=Math.round(correct/questions.length*100);if(profile.unlocked<world+2&&world<DATA.length-1)profile.unlocked=world+2;const badge=`World ${world+1} Conqueror`;if(!profile.badges.includes(badge))profile.badges.push(badge);if(world===9&&!profile.badges.includes('Form 4 Master'))profile.badges.push('Form 4 Master');localStorage.setItem('sejarahProfile',JSON.stringify(profile));const h=JSON.parse(localStorage.getItem('sejarahHistory')||'[]');h.push({name:profile.name,world:world+1,score,accuracy,errors:errors.length,date:new Date().toLocaleString()});localStorage.setItem('sejarahHistory',JSON.stringify(h.slice(-100)));const next=world<DATA.length-1?`<button onclick="startGame(${world+1})">进入 World ${world+2}</button>`:'';$('result').innerHTML=`<div class="card"><small>WORLD ${world+1} COMPLETE</small><h2>${DATA[world].enemy} 已被击败</h2><div class="scoreBig">${score}</div><p>正确率：${accuracy}%｜客观题：${correct}/${questions.length}｜Struktur：4/4｜Esei：8/8</p><div class="toolbar">${next}<button onclick="startGame(${world})">再次挑战</button><button class="secondary" onclick="location.reload()">返回主页</button></div></div><div class="card"><h2>错题订正簿</h2>${errors.length?errors.map((e,i)=>`<div class="reviewItem"><b>${i+1}. ${e.q}</b><br>你的答案：${e.chosen<0?'时间到':e.a[e.chosen]}<br>正确答案：${e.a[e.c]}<br>华语解释：${e.cn}<br>关键词：${e.kw}</div>`).join(''):'<p>本轮没有错题。</p>'}</div>`}
if(profile.name){renderMap();$('map').classList.remove('hide')}sync();