DATA.push(W('Penjaga Kesejahteraan','🤝',[
Q('Apakah matlamat utama Dasar Pendidikan Kebangsaan?',['Mewujudkan perpaduan melalui pendidikan','Menghapuskan semua sekolah','Menggantikan bahasa kebangsaan','Mengurangkan peluang belajar'],0,'国家教育政策的重要目标是通过共同教育方向促进团结。','Dasar Pendidikan Kebangsaan → perpaduan'),
Q('Laporan Razak 1956 menjadi asas kepada...',['Sistem pendidikan kebangsaan','Dasar luar negara','Rancangan pembangunan luar bandar','Pembentukan Malaysia'],0,'《拉萨报告》是国家教育制度的重要基础。','Laporan Razak 1956 → pendidikan kebangsaan'),
Q('Apakah bahasa pengantar utama yang diberi penekanan dalam pendidikan kebangsaan?',['Bahasa Melayu','Bahasa Latin','Bahasa Jepun','Bahasa Portugis'],0,'马来语被强调为国家教育体系中的主要语言。','bahasa pengantar → Bahasa Melayu'),
Q('Apakah tujuan penubuhan Rukun Negara?',['Memupuk perpaduan dan keharmonian','Menghapuskan pilihan raya','Menggantikan Perlembagaan','Membentuk kerajaan tentera'],0,'国家原则旨在加强团结、和谐与共同价值。','Rukun Negara → perpaduan'),
Q('Rukun Negara diperkenalkan selepas peristiwa...',['13 Mei 1969','31 Ogos 1957','16 September 1963','1 Februari 1948'],0,'国家原则是在1969年5月13日事件后推出。','13 Mei 1969 → Rukun Negara'),
Q('Prinsip pertama Rukun Negara ialah...',['Kepercayaan kepada Tuhan','Kesetiaan kepada Raja dan Negara','Keluhuran Perlembagaan','Kedaulatan Undang-undang'],0,'第一原则是信奉上苍。','prinsip pertama → Kepercayaan kepada Tuhan'),
Q('Apakah badan yang menyelaras dasar perpaduan selepas 13 Mei 1969?',['Majlis Gerakan Negara','Suruhanjaya Reid','Majlis Raja-Raja','Suruhanjaya Cobbold'],0,'国家行动理事会负责恢复秩序并协调团结措施。','MAGERAN → selepas 13 Mei'),
Q('Apakah tujuan Dasar Kebudayaan Kebangsaan?',['Membentuk identiti nasional','Menghapuskan budaya tempatan','Menggantikan semua bahasa','Menutup institusi seni'],0,'国家文化政策旨在建立共同国家认同。','Dasar Kebudayaan Kebangsaan → identiti nasional'),
Q('Sukan membantu pembinaan kesejahteraan negara melalui...',['Perpaduan dan kerjasama','Persaingan kaum','Pengasingan masyarakat','Penghapusan budaya'],0,'体育能通过共同参与促进团结与合作。','sukan → perpaduan'),
Q('Apakah kepentingan bahasa kebangsaan dalam negara majmuk?',['Menjadi alat komunikasi bersama','Memisahkan rakyat','Menghapuskan pendidikan','Menggantikan Perlembagaan'],0,'国语是多元社会的重要共同沟通工具。','bahasa kebangsaan → komunikasi bersama'),
Q('Program integrasi antara wilayah penting untuk...',['Mengukuhkan hubungan rakyat Semenanjung, Sabah dan Sarawak','Mengasingkan negeri','Mengurangkan mobiliti','Menghapuskan kerajaan negeri'],0,'跨区域融合计划有助于加强半岛、沙巴和砂拉越人民的关系。','integrasi wilayah → hubungan rakyat'),
Q('Mengapakah pendidikan dianggap penting dalam pembinaan negara?',['Membentuk rakyat berilmu dan bersatu','Meningkatkan konflik','Mengurangkan kemahiran','Melemahkan identiti'],0,'教育能培养有知识、具技能并团结的公民。','pendidikan → ilmu + perpaduan'),
Q('Apakah kesan mengamalkan prinsip Rukun Negara?',['Keharmonian masyarakat terpelihara','Kuasa asing bertambah','Undang-undang dihapuskan','Pentadbiran terganggu'],0,'实践国家原则有助于维持社会和谐。','Rukun Negara → keharmonian'),
Q('Situasi manakah menunjukkan usaha membina kesejahteraan negara?',['Murid pelbagai kaum menyertai aktiviti bersama','Sekolah mengasingkan pelajar mengikut kaum','Komuniti menolak bahasa kebangsaan','Rakyat enggan bekerjasama'],0,'不同族群共同参与活动体现融合与团结。','aktiviti bersama → integrasi'),
Q('Mengapakah identiti nasional penting?',['Mewujudkan rasa bangga dan kekitaan','Menghapuskan undang-undang','Menggalakkan perpecahan','Melemahkan kerajaan'],0,'国家认同能培养归属感、自豪感与团结。','identiti nasional → rasa kekitaan')
],'Jelaskan dua usaha membina perpaduan negara. [4 markah]',['Dasar Pendidikan Kebangsaan membentuk sistem pendidikan bersama.','Rukun Negara memupuk nilai bersama dalam kalangan rakyat.'],'Huraikan kepentingan usaha membina kesejahteraan negara. [8 markah]',['Perpaduan antara kaum dapat diperkukuh.','Identiti nasional dapat dibentuk.','Keharmonian masyarakat dapat dipelihara.','Kesannya, kestabilan dan kemajuan negara dapat diteruskan.']));