DATA.push(W('Penjaga Cabaran Malaysia','🧭',[
Q('Apakah cabaran utama selepas pembentukan Malaysia?',['Mengekalkan perpaduan dan keselamatan','Menghapuskan semua negeri','Menutup sempadan negara','Membubarkan kerajaan'],0,'成立马来西亚后，国家需要维护团结、安全与稳定。','cabaran selepas Malaysia → perpaduan + keselamatan'),
Q('Mengapakah Konfrontasi Indonesia berlaku?',['Indonesia menentang pembentukan Malaysia','Malaysia menutup sekolah','British membubarkan ASEAN','Singapura menolak perdagangan'],0,'印尼反对马来西亚的成立，因此发动对抗。','Konfrontasi → Indonesia menentang Malaysia'),
Q('Bilakah Konfrontasi Indonesia berakhir?',['1966','1963','1957','1971'],0,'马印对抗在1966年结束。','Konfrontasi tamat → 1966'),
Q('Apakah langkah Malaysia menghadapi Konfrontasi?',['Menggunakan diplomasi dan pertahanan','Menyerahkan Sabah','Membubarkan tentera','Menghentikan hubungan luar'],0,'马来西亚通过外交与防务维护国家安全。','langkah → diplomasi + pertahanan'),
Q('Negara manakah menuntut Sabah selepas pembentukan Malaysia?',['Filipina','Thailand','Jepun','Australia'],0,'菲律宾对沙巴提出主权要求。','tuntutan Sabah → Filipina'),
Q('Mengapakah Singapura keluar dari Malaysia?',['Perbezaan politik dan ekonomi','Bencana alam','Arahan PBB','Kekurangan penduduk'],0,'新加坡因政治、经济与种族课题上的分歧退出。','Singapura keluar → perbezaan politik + ekonomi'),
Q('Bilakah Singapura keluar dari Malaysia?',['9 Ogos 1965','16 September 1963','31 Ogos 1957','13 Mei 1969'],0,'新加坡于1965年8月9日退出马来西亚。','Singapura keluar → 9 Ogos 1965'),
Q('Siapakah mengumumkan pemisahan Singapura?',['Tunku Abdul Rahman','Tun Hussein Onn','Tun Dr. Ismail','Dato Onn Jaafar'],0,'东姑阿都拉曼宣布新加坡与马来西亚分离。','pemisahan → Tunku Abdul Rahman'),
Q('Apakah kesan pemisahan Singapura?',['Malaysia perlu menyusun semula hubungan politik dan ekonomi','Malaysia dibubarkan','Sabah keluar Malaysia','Perlembagaan dimansuhkan'],0,'分离后，马来西亚必须重新调整政治与经济关系。','kesan → susun semula politik + ekonomi'),
Q('Apakah tujuan utama menangani ancaman keselamatan?',['Menjamin kedaulatan negara','Mengurangkan pendidikan','Menghapuskan pilihan raya','Menutup ekonomi'],0,'处理安全威胁是为了保护国家主权与人民。','keselamatan → jamin kedaulatan'),
Q('Mengapakah kerjasama rakyat penting semasa krisis?',['Mengelakkan perpecahan','Melemahkan kerajaan','Menghentikan pentadbiran','Menghapus undang-undang'],0,'人民合作可避免分裂并加强国家稳定。','kerjasama rakyat → elak perpecahan'),
Q('Apakah nilai yang paling sesuai ketika menghadapi cabaran negara?',['Bersatu padu','Mementingkan diri','Mengabaikan undang-undang','Menolak rundingan'],0,'面对国家挑战时，团结是最关键的价值。','nilai → bersatu padu'),
Q('Apakah kepentingan rundingan dalam menyelesaikan konflik?',['Mengelakkan peperangan berpanjangan','Menambah permusuhan','Menghapus diplomasi','Melemahkan keamanan'],0,'谈判可避免长期冲突并恢复和平。','rundingan → elak konflik berpanjangan'),
Q('Apakah iktibar daripada Konfrontasi Indonesia?',['Hubungan diplomatik perlu dipelihara','Negara tidak perlu tentera','Perlembagaan tidak penting','Perpaduan tidak diperlukan'],0,'历史说明外交关系与国家安全必须同时维护。','iktibar → diplomasi + keselamatan'),
Q('Situasi: Rakyat menyebarkan khabar angin semasa krisis. Apakah tindakan terbaik?',['Semak fakta dan patuhi arahan rasmi','Sebarkan tanpa semakan','Abaikan undang-undang','Galakkan ketegangan'],0,'危机时期应核实资料并遵守官方指示，避免恐慌。','KBAT → semak fakta + arahan rasmi')
],'Jelaskan dua cabaran selepas pembentukan Malaysia. [4 markah]',['Malaysia menghadapi Konfrontasi Indonesia yang mengancam keselamatan negara.','Malaysia menghadapi perbezaan politik dan ekonomi sehingga Singapura berpisah.'],'Huraikan langkah menghadapi cabaran selepas pembentukan Malaysia. [8 markah]',['Kerajaan menggunakan saluran diplomatik untuk mengurangkan ketegangan.','Pertahanan negara diperkukuh bagi melindungi sempadan.','Rakyat digalakkan bersatu dan tidak terpengaruh dengan provokasi.','Kesannya, kedaulatan dan kestabilan negara dapat dipelihara.']));