DATA.push(W('Arkitek Kemakmuran','🏗️',[
Q('Apakah matlamat utama Dasar Ekonomi Baru (DEB)?',['Membasmi kemiskinan dan menyusun semula masyarakat','Menghapuskan sistem pendidikan','Menutup kawasan luar bandar','Mengurangkan peluang pekerjaan'],0,'新经济政策的两大目标是消除贫穷与重组社会。','DEB → membasmi kemiskinan + menyusun semula masyarakat'),
Q('DEB diperkenalkan pada tahun...',['1971','1957','1963','1991'],0,'DEB 于 1971 年推行。','DEB → 1971'),
Q('Apakah tempoh pelaksanaan DEB?',['1971 hingga 1990','1957 hingga 1963','1991 hingga 2000','2001 hingga 2010'],0,'DEB 的实施期是 1971–1990。','DEB → 1971–1990'),
Q('Mengapakah kemiskinan perlu dibasmi?',['Meningkatkan taraf hidup rakyat','Mengukuhkan kuasa asing','Mengurangkan pendidikan','Menutup peluang ekonomi'],0,'消除贫穷可提高人民生活水平。','membasmi kemiskinan → taraf hidup'),
Q('Apakah maksud menyusun semula masyarakat?',['Mengurangkan pengenalan kaum mengikut fungsi ekonomi','Mengasingkan kaum mengikut pekerjaan','Menghapuskan sektor pertanian','Memindahkan semua rakyat ke bandar'],0,'重组社会是减少族群与经济职业之间的固定联系。','susun semula masyarakat → fungsi ekonomi'),
Q('Agensi yang membantu pembangunan tanah dan luar bandar ialah...',['FELDA','MAGERAN','Suruhanjaya Reid','CLC'],0,'FELDA 发展土地与协助乡区居民。','FELDA → pembangunan tanah'),
Q('Apakah peranan FELDA?',['Membuka tanah baharu untuk pertanian','Menggubal perlembagaan','Mengurus pilihan raya','Menentukan dasar luar'],0,'FELDA 开辟新土地发展农业与安置垦殖民。','FELDA → tanah baharu'),
Q('Rancangan Buku Hijau bertujuan untuk...',['Menambah pengeluaran makanan','Mengurangkan hasil pertanian','Menghapuskan kegiatan desa','Menutup pasar tempatan'],0,'绿皮书计划鼓励增加粮食生产。','Buku Hijau → pengeluaran makanan'),
Q('Apakah kepentingan perindustrian kepada negara?',['Mewujudkan peluang pekerjaan','Mengurangkan pendapatan negara','Mengehadkan teknologi','Menghapuskan perdagangan'],0,'工业化创造就业并提高国家收入。','perindustrian → peluang pekerjaan'),
Q('Dasar Pembangunan Nasional diperkenalkan selepas...',['Tamatnya DEB','Pembentukan Malaysia','Kemerdekaan 1957','Penubuhan ASEAN'],0,'国家发展政策在 DEB 结束后推行。','DPN → selepas DEB'),
Q('Apakah matlamat Dasar Pembangunan Nasional?',['Meneruskan pembangunan seimbang','Menghapuskan semua sektor ekonomi','Mengasingkan wilayah','Mengurangkan penyertaan rakyat'],0,'DPN 延续均衡与公平发展的方向。','DPN → pembangunan seimbang'),
Q('Bagaimanakah pendidikan menyumbang kepada kemakmuran?',['Melahirkan tenaga kerja berkemahiran','Mengurangkan produktiviti','Menghapuskan inovasi','Mengehadkan peluang pekerjaan'],0,'教育培养熟练人力并提升生产力。','pendidikan → tenaga mahir'),
Q('Mengapakah pembangunan luar bandar penting?',['Mengurangkan jurang pembangunan','Menambah ketidakseimbangan','Mengasingkan penduduk','Mengurangkan kemudahan asas'],0,'乡区发展可缩小城乡差距。','luar bandar → kurangkan jurang'),
Q('Situasi manakah menunjukkan pembangunan seimbang?',['Kemudahan asas dibina di bandar dan luar bandar','Pelaburan hanya tertumpu di satu negeri','Sekolah desa ditutup','Peluang kerja dihadkan kepada satu kaum'],0,'均衡发展必须让不同地区都获得设施与机会。','pembangunan seimbang → semua wilayah'),
Q('Apakah nilai yang penting untuk menjayakan pembangunan negara?',['Kerjasama dan integriti','Perpecahan dan pilih kasih','Pembaziran dan rasuah','Kebergantungan kepada kuasa asing'],0,'合作与诚信能确保发展计划有效落实。','pembangunan → kerjasama + integriti')
],'Jelaskan dua usaha kerajaan membina kemakmuran negara. [4 markah]',['Kerajaan melaksanakan DEB untuk membasmi kemiskinan dan menyusun semula masyarakat.','Kerajaan membangunkan sektor perindustrian serta luar bandar bagi mewujudkan peluang ekonomi.'],'Huraikan kepentingan pembangunan ekonomi yang seimbang kepada negara. [8 markah]',['Taraf hidup rakyat dapat ditingkatkan.','Jurang ekonomi antara wilayah dan kaum dapat dikurangkan.','Peluang pekerjaan serta pendapatan negara bertambah.','Kesannya, kestabilan dan kemakmuran negara dapat diperkukuh.']));