const sejarahCatalog={
  'Form 4':[
    'Bab 1 Warisan Negara Bangsa','Bab 2 Kebangkitan Nasionalisme','Bab 3 Konflik Dunia dan Pendudukan Jepun di Negara Kita','Bab 4 Era Peralihan Kuasa British di Negara Kita','Bab 5 Persekutuan Tanah Melayu 1948','Bab 6 Ancaman Komunis dan Perisytiharan Darurat','Bab 7 Usaha ke Arah Kemerdekaan','Bab 8 Pilihan Raya','Bab 9 Perlembagaan Persekutuan Tanah Melayu 1957','Bab 10 Pemasyhuran Kemerdekaan'
  ],
  'Form 5':[
    'Bab 1 Kedaulatan Negara','Bab 2 Perlembagaan Persekutuan','Bab 3 Raja Berperlembagaan dan Demokrasi Berparlimen','Bab 4 Sistem Persekutuan','Bab 5 Pembentukan Malaysia','Bab 6 Cabaran Selepas Pembentukan Malaysia','Bab 7 Membina Kesejahteraan Negara','Bab 8 Membina Kemakmuran Negara','Bab 9 Dasar Luar Malaysia','Bab 10 Kecemerlangan Malaysia di Persada Dunia'
  ]
};

const seedQuestions=[
{year:2025,subject:'Sejarah',form:'Form 4',source:'SPM',paper:'Paper 2',chapter:'Bab 8 Pilihan Raya',topic:'Proses pilihan raya',type:'Struktur',marks:6,curriculum:'KSSM',verified:true,official:1,importance:92,gap:70,trial:82,fit:88,skill:76},
{year:2024,subject:'Sejarah',form:'Form 4',source:'SPM',paper:'Paper 2',chapter:'Bab 10 Pemasyhuran Kemerdekaan',topic:'Kesan kemerdekaan',type:'Esei',marks:8,curriculum:'KSSM',verified:true,official:1,importance:96,gap:62,trial:74,fit:92,skill:84},
{year:2023,subject:'Sejarah',form:'Form 4',source:'SPM',paper:'Paper 1',chapter:'Bab 5 Persekutuan Tanah Melayu 1948',topic:'Ciri Persekutuan Tanah Melayu 1948',type:'Objektif',marks:2,curriculum:'KSSM',verified:true,official:1,importance:86,gap:78,trial:65,fit:80,skill:70},
{year:2025,subject:'Sejarah',form:'Form 4',source:'Trial Negeri',paper:'Paper 2',chapter:'Bab 8 Pilihan Raya',topic:'Kepentingan pilihan raya',type:'Esei',marks:8,curriculum:'KSSM',verified:true,official:.6,importance:92,gap:70,trial:88,fit:91,skill:80},
{year:2025,subject:'Sejarah',form:'Form 5',source:'Trial SBP/MRSM',paper:'Paper 2',chapter:'Bab 1 Kedaulatan Negara',topic:'Kepentingan kedaulatan',type:'Esei',marks:8,curriculum:'KSSM',verified:true,official:.7,importance:95,gap:76,trial:86,fit:92,skill:85},
{year:2024,subject:'Sejarah',form:'Form 5',source:'SPM',paper:'Paper 2',chapter:'Bab 5 Pembentukan Malaysia',topic:'Faktor pembentukan Malaysia',type:'Struktur',marks:6,curriculum:'KSSM',verified:true,official:1,importance:96,gap:68,trial:84,fit:94,skill:86},
{year:2023,subject:'Sejarah',form:'Form 5',source:'SPM',paper:'Paper 2',chapter:'Bab 9 Dasar Luar Malaysia',topic:'Asas penggubalan dasar luar',type:'Esei',marks:8,curriculum:'KSSM',verified:true,official:1,importance:91,gap:75,trial:79,fit:90,skill:83},
{year:2022,subject:'Sejarah',form:'Form 5',source:'SPM',paper:'Paper 1',chapter:'Bab 3 Raja Berperlembagaan dan Demokrasi Berparlimen',topic:'Ciri demokrasi berparlimen',type:'Objektif',marks:2,curriculum:'KSSM',verified:true,official:1,importance:94,gap:73,trial:77,fit:89,skill:81},
{year:2024,subject:'Mathematics',form:'Form 4',source:'SPM',paper:'Paper 2',chapter:'Quadratic Functions',topic:'Graph and roots',type:'Structured',marks:6,curriculum:'KSSM',verified:true,official:1,importance:94,gap:65,trial:79,fit:92,skill:86},
{year:2023,subject:'Mathematics',form:'Form 5',source:'SPM',paper:'Paper 1',chapter:'Statistics',topic:'Measures of dispersion',type:'Objective',marks:3,curriculum:'KSSM',verified:true,official:1,importance:90,gap:72,trial:75,fit:88,skill:80},
{year:2022,subject:'Mathematics',form:'Form 4',source:'SPM',paper:'Paper 2',chapter:'Graphs of Motion',topic:'Distance-time graph',type:'Structured',marks:7,curriculum:'KSSM',verified:true,official:1,importance:92,gap:80,trial:83,fit:95,skill:88},
{year:2024,subject:'Science',form:'Form 4',source:'SPM',paper:'Paper 2',chapter:'Force and Motion',topic:'Experiment variables',type:'Structured',marks:8,curriculum:'KSSM',verified:true,official:1,importance:96,gap:68,trial:86,fit:96,skill:92},
{year:2023,subject:'Science',form:'Form 5',source:'SPM',paper:'Paper 2',chapter:'Electricity and Magnetism',topic:'Application of electromagnet',type:'Essay',marks:10,curriculum:'KSSM',verified:true,official:1,importance:91,gap:79,trial:82,fit:91,skill:84},
{year:2024,subject:'Bahasa Melayu',form:'Form 5',source:'SPM',paper:'Paper 1',chapter:'Karangan',topic:'Kesihatan dan gaya hidup',type:'Esei',marks:70,curriculum:'KSSM',verified:true,official:1,importance:95,gap:66,trial:80,fit:96,skill:90},
{year:2023,subject:'Bahasa Melayu',form:'Form 4',source:'SPM',paper:'Paper 2',chapter:'Sintaksis',topic:'Ayat aktif dan pasif',type:'Struktur',marks:6,curriculum:'KSSM',verified:true,official:1,importance:92,gap:76,trial:84,fit:94,skill:88},
{year:2024,subject:'English',form:'Form 5',source:'SPM',paper:'Paper 2',chapter:'Writing',topic:'Article / review',type:'Extended writing',marks:20,curriculum:'KSSM',verified:true,official:1,importance:94,gap:70,trial:81,fit:94,skill:91}
];

const STORAGE_KEY='spmqi_imported_v3';
let imported=loadImported();
let questions=[...seedQuestions,...imported];
const state={subject:'all',form:'all',chapter:'all',year:'all',paper:'all',type:'all',source:'all',verify:'all',search:''};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function safe(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function loadImported(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
function saveImported(){localStorage.setItem(STORAGE_KEY,JSON.stringify(imported))}
function uniq(k,rows=questions){return [...new Set(rows.map(q=>q[k]).filter(v=>v!==''&&v!=null))].sort((a,b)=>typeof a==='number'?b-a:String(a).localeCompare(String(b)))}
function fill(id,values,allLabel){const el=$(id);const current=el.value;el.innerHTML=`<option value="all">${allLabel}</option>`+values.map(v=>`<option value="${safe(v)}">${safe(v)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current;else el.value='all'}
function refreshFilters(){
 fill('#subjectFilter',uniq('subject'),'全部科目');
 const subjectRows=state.subject==='all'?questions:questions.filter(q=>q.subject===state.subject);
 fill('#formFilter',uniq('form',subjectRows),'全部 Form');
 const formRows=subjectRows.filter(q=>state.form==='all'||q.form===state.form);
 fill('#chapterFilter',uniq('chapter',formRows),'全部章节');
 fill('#yearFilter',uniq('year'),'全部年份');fill('#paperFilter',uniq('paper'),'全部 Paper');fill('#typeFilter',uniq('type'),'全部题型');fill('#sourceFilter',uniq('source'),'全部来源');
}
function filtered(){return questions.filter(q=>(state.subject==='all'||q.subject===state.subject)&&(state.form==='all'||q.form===state.form)&&(state.chapter==='all'||q.chapter===state.chapter)&&(state.year==='all'||String(q.year)===String(state.year))&&(state.paper==='all'||q.paper===state.paper)&&(state.type==='all'||q.type===state.type)&&(state.source==='all'||q.source===state.source)&&(state.verify==='all'||(state.verify==='verified'?q.verified:!q.verified))&&(!state.search||`${q.chapter} ${q.topic} ${q.subject} ${q.source} ${q.form}`.toLowerCase().includes(state.search.toLowerCase())))}
function num(v,fallback=50){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):fallback}
function score(q){const age=Math.max(0,new Date().getFullYear()-Number(q.year));const recency=Math.max(25,100-age*9);const curriculumPenalty=String(q.curriculum).toUpperCase()==='KSSM'?0:18;const unverifiedPenalty=q.verified?0:8;const raw=25*(recency*num(q.official,.5)/100)+20*num(q.importance)/100+15*num(q.gap)/100+15*num(q.trial)/100+10*num(q.fit)/100+10*num(q.skill)/100+5*(q.verified?1:.4)-curriculumPenalty-unverifiedPenalty;return Math.round(Math.max(0,Math.min(100,raw)))}
function grouped(rows){const map={};rows.forEach(q=>{const k=`${q.subject}||${q.form||'Unknown'}||${q.chapter}`;(map[k]??=[]).push(q)});return Object.entries(map).map(([k,items])=>{const [subject,form,chapter]=k.split('||');return{subject,form,chapter,items,score:Math.round(items.reduce((s,q)=>s+score(q),0)/items.length),last:Math.max(...items.map(x=>Number(x.year))),marks:items.reduce((s,x)=>s+Number(x.marks||0),0),verified:items.filter(x=>x.verified).length/items.length,topType:mode(items.map(x=>x.type))}}).sort((a,b)=>b.score-a.score)}
function mode(arr){return [...new Set(arr)].sort((a,b)=>arr.filter(x=>x===b).length-arr.filter(x=>x===a).length)[0]||'—'}
function cls(n){return n>=80?'high':n>=65?'medium':n>=50?'normal':'low'}
function render(){const rows=filtered();const groups=grouped(rows);$('#stats').innerHTML=[['题目记录',rows.length,'当前筛选'],['涉及章节',groups.length,'按 Form 分类'],['累计分数',rows.reduce((s,q)=>s+Number(q.marks||0),0),'marks'],['验证比例',rows.length?Math.round(rows.filter(q=>q.verified).length/rows.length*100)+'%':'0%','teacher checked']].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');renderHeat(groups);renderPriority(groups);renderBars(rows);renderTable(rows);renderPrediction(groups);renderCatalog()}
function renderPriority(groups){$('#priorityList').innerHTML=groups.slice(0,6).map(g=>`<div class="priority-item"><div class="priority-top"><span class="priority-name">${safe(g.chapter)}<small>${safe(g.subject)} · ${safe(g.form)}</small></span><strong class="score ${cls(g.score)}">${g.score}</strong></div><div class="meter"><i style="width:${g.score}%"></i></div><div class="reason">最近 ${g.last} · ${g.marks} 分 · ${g.items.length} 条 · 常见题型 ${safe(g.topType)}</div></div>`).join('')||'<div class="empty">没有符合条件的数据</div>'}
function renderHeat(groups){const years=uniq('year').slice(0,6).sort();let html=`<div class="heat-row header"><span>章节</span>${years.map(y=>`<span>${y}</span>`).join('')}</div>`;groups.slice(0,8).forEach(g=>{html+=`<div class="heat-row"><span class="heat-label" title="${safe(g.form+' '+g.chapter)}">${safe(g.form.replace('Form ','F')+' · '+g.chapter)}</span>${years.map(y=>{const value=g.items.filter(x=>String(x.year)===String(y)).reduce((s,x)=>s+Number(x.marks||0),0);const level=value===0?0:value<5?1:value<8?2:value<12?3:4;return`<span class="heat-cell heat-${level}">${value||'—'}</span>`}).join('')}</div>`});$('#heatmap').innerHTML=html||'<div class="empty">暂无数据</div>'}
function renderBars(rows){const years=uniq('year').sort();const values=years.map(y=>({y,v:rows.filter(q=>String(q.year)===String(y)).reduce((s,q)=>s+Number(q.marks||0),0)}));const max=Math.max(1,...values.map(x=>x.v));$('#bars').innerHTML=values.map(x=>`<div class="bar-group"><div class="bar" data-value="${x.v} marks" style="height:${Math.max(4,x.v/max*165)}px"></div><span>${x.y}</span></div>`).join('')}
function renderTable(rows){$('#resultCount').textContent=`${rows.length} records`;$('#questionTable').innerHTML=[...rows].sort((a,b)=>b.year-a.year).map(q=>`<tr><td>${q.year}</td><td><strong>${safe(q.subject)}</strong></td><td>${safe(q.form||'—')}</td><td>${safe(q.source)}</td><td>${safe(q.paper)}</td><td><strong>${safe(q.chapter)}</strong><span class="muted">${safe(q.topic)}</span></td><td>${safe(q.type)}</td><td>${q.marks}</td><td class="${q.verified?'verified':'unverified'}">${q.verified?'已验证':'待审核'}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">没有符合条件的题目</td></tr>'}
function renderPrediction(groups){$('#predictionBoard').innerHTML=groups.map(g=>{const conf=Math.round(g.verified*100*Math.min(1,g.items.length/3));const reason=g.score>=80?'信号较强：优先完成完整结构题与 Esei 训练，同时核对原始来源。':g.score>=65?'具有明显复习价值：掌握核心事实、kata tugas 与常见题型。':'维持基础覆盖，不建议完全忽略。';return`<div class="prediction-item"><div><h3>${safe(g.chapter)}</h3><div class="prediction-meta"><span>${safe(g.subject)}</span><span>${safe(g.form)}</span><span>最近 ${g.last}</span><span>${g.items.length} 条记录</span><span>主要 ${safe(g.topType)}</span></div><p class="reason">${reason}</p></div><div class="prediction-score"><strong class="score ${cls(g.score)}">${g.score}</strong><span class="confidence">置信度 ${conf}%</span></div></div>`}).join('')||'<div class="empty">暂无预测结果</div>'}
function renderCatalog(){const box=$('#chapterCatalog');if(!box)return;box.innerHTML=Object.entries(sejarahCatalog).map(([form,chapters])=>`<section class="catalog-column"><h3>${form}</h3>${chapters.map((c,i)=>{const count=questions.filter(q=>q.subject==='Sejarah'&&q.form===form&&q.chapter===c).length;return`<button class="catalog-item" data-form="${form}" data-chapter="${safe(c)}"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${safe(c)}</strong><small>${count} 条题目记录</small></div></button>`}).join('')}</section>`).join('');$$('.catalog-item').forEach(btn=>btn.onclick=()=>{state.subject='Sejarah';state.form=btn.dataset.form;state.chapter=btn.dataset.chapter;refreshFilters();$('#subjectFilter').value='Sejarah';$('#formFilter').value=state.form;$('#chapterFilter').value=state.chapter;$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='questions'));$$('.view').forEach(x=>x.classList.remove('active'));$('#questionsView').classList.add('active');render()})}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row);return rows}
function normalizeRecord(obj){const bool=String(obj.verified).trim().toLowerCase();return{year:Number(obj.year),subject:String(obj.subject||'').trim(),form:String(obj.form||'').trim(),source:String(obj.source||'').trim(),paper:String(obj.paper||'').trim(),chapter:String(obj.chapter||'').trim(),topic:String(obj.topic||'').trim(),type:String(obj.type||'').trim(),marks:Number(obj.marks),curriculum:String(obj.curriculum||'KSSM').trim(),verified:['true','1','yes','verified','已验证'].includes(bool),official:num(obj.official,.5),importance:num(obj.importance,50),gap:num(obj.gap,50),trial:num(obj.trial,50),fit:num(obj.fit,50),skill:num(obj.skill,50)}}
function recordKey(q){return [q.year,q.subject,q.form,q.source,q.paper,q.chapter,q.topic,q.type].map(x=>String(x).toLowerCase().trim()).join('|')}
$('#csvFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const result=$('#importResult');try{const matrix=parseCSV((await file.text()).replace(/^\uFEFF/,''));if(matrix.length<2)throw new Error('CSV 没有资料行');const headers=matrix[0].map(h=>h.trim());const required=['year','subject','form','source','paper','chapter','topic','type','marks','curriculum','verified'];const missing=required.filter(h=>!headers.includes(h));if(missing.length)throw new Error(`缺少字段：${missing.join(', ')}`);const existing=new Set(questions.map(recordKey));let added=0,duplicates=0,invalid=0,warnings=0;matrix.slice(1).forEach(values=>{const raw=Object.fromEntries(headers.map((h,i)=>[h,values[i]??'']));const q=normalizeRecord(raw);if(!q.year||!q.subject||!q.form||!q.source||!q.paper||!q.chapter||!q.topic||!q.type||!Number.isFinite(q.marks)){invalid++;return}if(q.subject==='Sejarah'&&sejarahCatalog[q.form]&&!sejarahCatalog[q.form].includes(q.chapter))warnings++;const key=recordKey(q);if(existing.has(key)){duplicates++;return}existing.add(key);imported.push(q);added++});saveImported();questions=[...seedQuestions,...imported];refreshFilters();render();result.innerHTML=`<strong>导入完成</strong><br>新增 ${added} 条 · 重复 ${duplicates} 条 · 无效 ${invalid} 条 · 章节名称警告 ${warnings} 条`;result.className='import-result success'}catch(err){result.textContent=`导入失败：${err.message}`;result.className='import-result error'}finally{e.target.value=''}})
$('#clearImportedBtn').addEventListener('click',()=>{if(!confirm('确定清除这台浏览器导入的全部题目？'))return;imported=[];saveImported();questions=[...seedQuestions];refreshFilters();render();$('#importResult').textContent='本机导入资料已清除。';$('#importResult').className='import-result muted'})
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
$('#exportBtn').addEventListener('click',()=>{const headers=['year','subject','form','source','paper','chapter','topic','type','marks','curriculum','verified','official','importance','gap','trial','fit','skill'];const lines=[headers.join(','),...filtered().map(q=>headers.map(h=>csvEscape(q[h])).join(','))];const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='spm-question-export.csv';a.click();URL.revokeObjectURL(a.href)})
['subject','form','chapter','year','paper','type','source'].forEach(k=>{$(`#${k}Filter`).addEventListener('change',e=>{state[k]=e.target.value;if(k==='subject'){state.form='all';state.chapter='all'}if(k==='form')state.chapter='all';refreshFilters();render()})});$('#verifyFilter').addEventListener('change',e=>{state.verify=e.target.value;render()});$('#searchInput').addEventListener('input',e=>{state.search=e.target.value.trim();render()});$('#resetBtn').addEventListener('click',()=>{Object.assign(state,{subject:'all',form:'all',chapter:'all',year:'all',paper:'all',type:'all',source:'all',verify:'all',search:''});refreshFilters();$$('.filters select').forEach(x=>x.value='all');$('#searchInput').value='';render()});$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#${btn.dataset.view}View`).classList.add('active')}));
refreshFilters();render();