const sejarahCatalog={
  'Form 4':['Bab 1 Warisan Negara Bangsa','Bab 2 Kebangkitan Nasionalisme','Bab 3 Konflik Dunia dan Pendudukan Jepun di Negara Kita','Bab 4 Era Peralihan Kuasa British di Negara Kita','Bab 5 Persekutuan Tanah Melayu 1948','Bab 6 Ancaman Komunis dan Perisytiharan Darurat','Bab 7 Usaha ke Arah Kemerdekaan','Bab 8 Pilihan Raya','Bab 9 Perlembagaan Persekutuan Tanah Melayu 1957','Bab 10 Pemasyhuran Kemerdekaan'],
  'Form 5':['Bab 1 Kedaulatan Negara','Bab 2 Perlembagaan Persekutuan','Bab 3 Raja Berperlembagaan dan Demokrasi Berparlimen','Bab 4 Sistem Persekutuan','Bab 5 Pembentukan Malaysia','Bab 6 Cabaran Selepas Pembentukan Malaysia','Bab 7 Membina Kesejahteraan Negara','Bab 8 Membina Kemakmuran Negara','Bab 9 Dasar Luar Malaysia','Bab 10 Kecemerlangan Malaysia di Persada Dunia']
};

const seedQuestions=[
 {question_id:'SJ-2025-SPM-P2-Q3',year:2025,subject:'Sejarah',form:'Form 4',source:'SPM',state:'National',paper:'Paper 2',section:'Bahagian A',question_no:'3',chapter:'Bab 8 Pilihan Raya',topic:'Proses pilihan raya',command_word:'Jelaskan',cognitive:'Memahami',skills:'fakta|urutan',type:'Struktur',marks:6,curriculum:'KSSM',verified:true,duplicate_group:'',source_url:'',official:1,importance:92,gap:70,trial:82,fit:88,skill:76},
 {question_id:'SJ-2024-SPM-P2-Q8',year:2024,subject:'Sejarah',form:'Form 4',source:'SPM',state:'National',paper:'Paper 2',section:'Bahagian B',question_no:'8',chapter:'Bab 10 Pemasyhuran Kemerdekaan',topic:'Kesan kemerdekaan',command_word:'Huraikan',cognitive:'Menganalisis',skills:'fakta|kesan|esei',type:'Esei',marks:8,curriculum:'KSSM',verified:true,duplicate_group:'',source_url:'',official:1,importance:96,gap:62,trial:74,fit:92,skill:84},
 {question_id:'SJ-2023-SPM-P1-Q18',year:2023,subject:'Sejarah',form:'Form 4',source:'SPM',state:'National',paper:'Paper 1',section:'Kertas 1',question_no:'18',chapter:'Bab 5 Persekutuan Tanah Melayu 1948',topic:'Ciri Persekutuan Tanah Melayu 1948',command_word:'Pilih',cognitive:'Mengingat',skills:'fakta',type:'Objektif',marks:1,curriculum:'KSSM',verified:true,duplicate_group:'',source_url:'',official:1,importance:86,gap:78,trial:65,fit:80,skill:70},
 {question_id:'SJ-2025-JHR-P2-Q7',year:2025,subject:'Sejarah',form:'Form 4',source:'Trial Negeri',state:'Johor',paper:'Paper 2',section:'Bahagian B',question_no:'7',chapter:'Bab 8 Pilihan Raya',topic:'Kepentingan pilihan raya',command_word:'Huraikan',cognitive:'Menganalisis',skills:'fakta|kepentingan|KBAT',type:'Esei',marks:8,curriculum:'KSSM',verified:true,duplicate_group:'TR25-SJ-F4B8-01',source_url:'',official:.6,importance:92,gap:70,trial:88,fit:91,skill:80},
 {question_id:'SJ-2025-SBP-P2-Q7',year:2025,subject:'Sejarah',form:'Form 4',source:'Trial SBP/MRSM',state:'SBP',paper:'Paper 2',section:'Bahagian B',question_no:'7',chapter:'Bab 8 Pilihan Raya',topic:'Kepentingan pilihan raya dalam demokrasi',command_word:'Huraikan',cognitive:'Menganalisis',skills:'fakta|kepentingan|KBAT',type:'Esei',marks:8,curriculum:'KSSM',verified:false,duplicate_group:'TR25-SJ-F4B8-01',source_url:'',official:.7,importance:92,gap:70,trial:88,fit:91,skill:80},
 {question_id:'SJ-2025-MRSM-P2-Q8',year:2025,subject:'Sejarah',form:'Form 5',source:'Trial SBP/MRSM',state:'MRSM',paper:'Paper 2',section:'Bahagian B',question_no:'8',chapter:'Bab 1 Kedaulatan Negara',topic:'Kepentingan kedaulatan',command_word:'Bincangkan',cognitive:'Menilai',skills:'fakta|kepentingan|esei',type:'Esei',marks:8,curriculum:'KSSM',verified:true,duplicate_group:'',source_url:'',official:.7,importance:95,gap:76,trial:86,fit:92,skill:85},
 {question_id:'SJ-2024-SPM-P2-Q4',year:2024,subject:'Sejarah',form:'Form 5',source:'SPM',state:'National',paper:'Paper 2',section:'Bahagian A',question_no:'4',chapter:'Bab 5 Pembentukan Malaysia',topic:'Faktor pembentukan Malaysia',command_word:'Jelaskan',cognitive:'Memahami',skills:'fakta|sebab',type:'Struktur',marks:6,curriculum:'KSSM',verified:true,duplicate_group:'',source_url:'',official:1,importance:96,gap:68,trial:84,fit:94,skill:86},
 {question_id:'SJ-2023-SPM-P2-Q9',year:2023,subject:'Sejarah',form:'Form 5',source:'SPM',state:'National',paper:'Paper 2',section:'Bahagian B',question_no:'9',chapter:'Bab 9 Dasar Luar Malaysia',topic:'Asas penggubalan dasar luar',command_word:'Huraikan',cognitive:'Menganalisis',skills:'fakta|faktor|esei',type:'Esei',marks:8,curriculum:'KSSM',verified:true,duplicate_group:'',source_url:'',official:1,importance:91,gap:75,trial:79,fit:90,skill:83},
 {question_id:'MT-2024-SPM-P2-Q10',year:2024,subject:'Mathematics',form:'Form 4',source:'SPM',state:'National',paper:'Paper 2',section:'Section B',question_no:'10',chapter:'Quadratic Functions',topic:'Graph and roots',command_word:'Calculate',cognitive:'Apply',skills:'graph|roots|algebra',type:'Structured',marks:6,curriculum:'KSSM',verified:true,duplicate_group:'',source_url:'',official:1,importance:94,gap:65,trial:79,fit:92,skill:86},
 {question_id:'SC-2024-SPM-P2-Q2',year:2024,subject:'Science',form:'Form 4',source:'SPM',state:'National',paper:'Paper 2',section:'Section A',question_no:'2',chapter:'Force and Motion',topic:'Experiment variables',command_word:'State',cognitive:'Apply',skills:'variables|experiment',type:'Structured',marks:8,curriculum:'KSSM',verified:true,duplicate_group:'',source_url:'',official:1,importance:96,gap:68,trial:86,fit:96,skill:92}
];

const STORAGE_KEY='spmqi_imported_v4';
let imported=loadImported();
let questions=[...seedQuestions,...imported].map(enrichRecord);
const state={subject:'all',form:'all',chapter:'all',year:'all',paper:'all',type:'all',source:'all',verify:'all',search:''};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function safe(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function loadImported(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
function saveImported(){localStorage.setItem(STORAGE_KEY,JSON.stringify(imported))}
function num(v,fallback=50){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):fallback}
function slug(v){return String(v||'X').toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,18)||'X'}
function createId(q,index=0){return `${slug(q.subject).slice(0,3)}-${q.year||'YEAR'}-${slug(q.source).slice(0,4)}-${slug(q.paper).slice(0,3)}-${slug(q.question_no||index+1)}`}
function enrichRecord(q,index=0){const out={...q};out.question_id=String(out.question_id||'').trim()||createId(out,index);out.state=String(out.state||'').trim();out.section=String(out.section||'').trim();out.question_no=String(out.question_no||'').trim();out.command_word=String(out.command_word||'').trim();out.cognitive=String(out.cognitive||'').trim();out.skills=String(out.skills||'').trim();out.duplicate_group=String(out.duplicate_group||'').trim();out.source_url=String(out.source_url||'').trim();return out}
function uniq(k,rows=questions){return [...new Set(rows.map(q=>q[k]).filter(v=>v!==''&&v!=null))].sort((a,b)=>typeof a==='number'?b-a:String(a).localeCompare(String(b)))}
function fill(id,values,allLabel){const el=$(id);const current=el.value;el.innerHTML=`<option value="all">${allLabel}</option>`+values.map(v=>`<option value="${safe(v)}">${safe(v)}</option>`).join('');el.value=[...el.options].some(o=>o.value===current)?current:'all'}
function refreshFilters(){fill('#subjectFilter',uniq('subject'),'全部科目');const subjectRows=state.subject==='all'?questions:questions.filter(q=>q.subject===state.subject);fill('#formFilter',uniq('form',subjectRows),'全部 Form');const formRows=subjectRows.filter(q=>state.form==='all'||q.form===state.form);fill('#chapterFilter',uniq('chapter',formRows),'全部章节');fill('#yearFilter',uniq('year'),'全部年份');fill('#paperFilter',uniq('paper'),'全部 Paper');fill('#typeFilter',uniq('type'),'全部题型');fill('#sourceFilter',uniq('source'),'全部来源')}
function filtered(){const needle=state.search.toLowerCase();return questions.filter(q=>(state.subject==='all'||q.subject===state.subject)&&(state.form==='all'||q.form===state.form)&&(state.chapter==='all'||q.chapter===state.chapter)&&(state.year==='all'||String(q.year)===String(state.year))&&(state.paper==='all'||q.paper===state.paper)&&(state.type==='all'||q.type===state.type)&&(state.source==='all'||q.source===state.source)&&(state.verify==='all'||(state.verify==='verified'?q.verified:!q.verified))&&(!needle||`${q.question_id} ${q.chapter} ${q.topic} ${q.subject} ${q.source} ${q.form} ${q.command_word} ${q.skills} ${q.question_no}`.toLowerCase().includes(needle)))}
function completeness(q){const fields=['question_id','year','subject','form','source','paper','chapter','topic','type','marks','curriculum','state','section','question_no','command_word','cognitive','skills'];const present=fields.filter(k=>q[k]!==''&&q[k]!=null&&Number.isFinite(q[k])!==false).length;return Math.round(present/fields.length*100)}
function duplicateWeight(q){if(!q.duplicate_group)return 1;const cluster=questions.filter(x=>x.duplicate_group===q.duplicate_group).sort((a,b)=>(Number(b.verified)-Number(a.verified))||(completeness(b)-completeness(a)));return cluster[0]?.question_id===q.question_id?1:.25}
function recordScore(q){const age=Math.max(0,new Date().getFullYear()-Number(q.year));const recency=Math.max(25,100-age*9);const curriculumPenalty=String(q.curriculum).toUpperCase()==='KSSM'?0:18;const verification=q.verified?1:.45;const base=25*(recency*num(q.official,.5)/100)+20*num(q.importance)/100+15*num(q.gap)/100+15*num(q.trial)/100+10*num(q.fit)/100+10*num(q.skill)/100+5*verification-curriculumPenalty;const quality=.55+.45*(completeness(q)/100);return Math.round(Math.max(0,Math.min(100,base*quality*duplicateWeight(q))))}
function effectiveMarks(q){return Number(q.marks||0)*duplicateWeight(q)*(q.verified?1:.65)*(completeness(q)/100)}
function grouped(rows){const map={};rows.forEach(q=>{const k=`${q.subject}||${q.form||'Unknown'}||${q.chapter}`;(map[k]??=[]).push(q)});return Object.entries(map).map(([k,items])=>{const [subject,form,chapter]=k.split('||');const independent=new Set(items.map(x=>x.duplicate_group||x.question_id)).size;return{subject,form,chapter,items,score:Math.round(items.reduce((s,q)=>s+recordScore(q),0)/items.length),last:Math.max(...items.map(x=>Number(x.year))),marks:Math.round(items.reduce((s,x)=>s+effectiveMarks(x),0)*10)/10,verified:items.filter(x=>x.verified).length/items.length,topType:mode(items.map(x=>x.type)),independent,quality:Math.round(items.reduce((s,x)=>s+completeness(x),0)/items.length)}}).sort((a,b)=>b.score-a.score)}
function mode(arr){return [...new Set(arr)].sort((a,b)=>arr.filter(x=>x===b).length-arr.filter(x=>x===a).length)[0]||'—'}
function cls(n){return n>=80?'high':n>=65?'medium':n>=50?'normal':'low'}
function qualityLabel(q){const c=completeness(q);if(!q.verified)return`<span class="quality-badge pending">待审核 · ${c}%</span>`;if(duplicateWeight(q)<1)return`<span class="quality-badge duplicate">重复群 · ${c}%</span>`;return`<span class="quality-badge good">可靠 · ${c}%</span>`}
function render(){const rows=filtered(),groups=grouped(rows);$('#stats').innerHTML=[['题目记录',rows.length,'当前筛选'],['独立题源',new Set(rows.map(q=>q.duplicate_group||q.question_id)).size,'去重后'],['有效分数',Math.round(rows.reduce((s,q)=>s+effectiveMarks(q),0)),'quality adjusted'],['平均完整度',rows.length?Math.round(rows.reduce((s,q)=>s+completeness(q),0)/rows.length)+'%':'0%','data completeness']].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');renderHeat(groups);renderPriority(groups);renderBars(rows);renderTable(rows);renderPrediction(groups);renderCatalog();renderQuality(rows)}
function renderPriority(groups){$('#priorityList').innerHTML=groups.slice(0,6).map(g=>`<div class="priority-item"><div class="priority-top"><span class="priority-name">${safe(g.chapter)}<small>${safe(g.subject)} · ${safe(g.form)}</small></span><strong class="score ${cls(g.score)}">${g.score}</strong></div><div class="meter"><i style="width:${g.score}%"></i></div><div class="reason">最近 ${g.last} · 有效 ${g.marks} 分 · ${g.independent} 个独立题源 · 完整度 ${g.quality}%</div></div>`).join('')||'<div class="empty">没有符合条件的数据</div>'}
function renderHeat(groups){const years=uniq('year').slice(0,6).sort();let html=`<div class="heat-row header"><span>章节</span>${years.map(y=>`<span>${y}</span>`).join('')}</div>`;groups.slice(0,8).forEach(g=>{html+=`<div class="heat-row"><span class="heat-label" title="${safe(g.form+' '+g.chapter)}">${safe((g.form||'').replace('Form ','F')+' · '+g.chapter)}</span>${years.map(y=>{const value=Math.round(g.items.filter(x=>String(x.year)===String(y)).reduce((s,x)=>s+effectiveMarks(x),0));const level=value===0?0:value<5?1:value<8?2:value<12?3:4;return`<span class="heat-cell heat-${level}">${value||'—'}</span>`}).join('')}</div>`});$('#heatmap').innerHTML=html||'<div class="empty">暂无数据</div>'}
function renderBars(rows){const years=uniq('year').sort();const values=years.map(y=>({y,v:Math.round(rows.filter(q=>String(q.year)===String(y)).reduce((s,q)=>s+effectiveMarks(q),0))}));const max=Math.max(1,...values.map(x=>x.v));$('#bars').innerHTML=values.map(x=>`<div class="bar-group"><div class="bar" data-value="${x.v} effective marks" style="height:${Math.max(4,x.v/max*165)}px"></div><span>${x.y}</span></div>`).join('')}
function renderTable(rows){$('#resultCount').textContent=`${rows.length} records`;$('#questionTable').innerHTML=[...rows].sort((a,b)=>b.year-a.year).map(q=>`<tr><td><strong>${safe(q.question_id)}</strong><span class="muted">${q.year}</span></td><td><strong>${safe(q.subject)}</strong><span class="muted">${safe(q.form||'—')}</span></td><td><strong>${safe(q.source)}</strong><span class="muted">${safe(q.state||'未填写')}</span></td><td><strong>${safe(q.paper)}</strong><span class="muted">${safe(q.section||'—')} · Q${safe(q.question_no||'—')}</span></td><td><strong>${safe(q.chapter)}</strong><span class="muted">${safe(q.topic)}</span></td><td><strong>${safe(q.command_word||'—')}</strong><span class="muted">${safe(q.skills||'—')}</span></td><td>${safe(q.type)}<span class="muted">${safe(q.cognitive||'—')}</span></td><td>${q.marks}</td><td>${qualityLabel(q)}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">没有符合条件的题目</td></tr>'}
function renderPrediction(groups){$('#predictionBoard').innerHTML=groups.map(g=>{const sampleFactor=Math.min(1,g.independent/4),conf=Math.round(g.verified*sampleFactor*(g.quality/100)*100);const reason=g.score>=80?'高优先：独立来源与质量信号较强，安排完整结构题及 Esei 训练。':g.score>=65?'较高优先：掌握核心事实、kata tugas 与主要题型，并补足资料缺口。':'维持基础覆盖；当前信号或资料量不足，不宜过度押题。';return`<div class="prediction-item"><div><h3>${safe(g.chapter)}</h3><div class="prediction-meta"><span>${safe(g.subject)}</span><span>${safe(g.form)}</span><span>最近 ${g.last}</span><span>${g.independent} 独立来源</span><span>主要 ${safe(g.topType)}</span><span>资料 ${g.quality}%</span></div><p class="reason">${reason}</p></div><div class="prediction-score"><strong class="score ${cls(g.score)}">${g.score}</strong><span class="confidence">置信度 ${conf}%</span></div></div>`}).join('')||'<div class="empty">暂无预测结果</div>'}
function renderCatalog(){const box=$('#chapterCatalog');if(!box)return;box.innerHTML=Object.entries(sejarahCatalog).map(([form,chapters])=>`<section class="catalog-column"><h3>${form}</h3>${chapters.map((c,i)=>{const items=questions.filter(q=>q.subject==='Sejarah'&&q.form===form&&q.chapter===c),years=new Set(items.map(x=>x.year)).size,verified=items.filter(x=>x.verified).length;return`<button class="catalog-item" data-form="${form}" data-chapter="${safe(c)}"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${safe(c)}</strong><small>${items.length} 题 · ${years} 年份 · ${verified} 已验证</small></div></button>`}).join('')}</section>`).join('');$$('.catalog-item').forEach(btn=>btn.onclick=()=>{Object.assign(state,{subject:'Sejarah',form:btn.dataset.form,chapter:btn.dataset.chapter});refreshFilters();$('#subjectFilter').value='Sejarah';$('#formFilter').value=state.form;$('#chapterFilter').value=state.chapter;switchView('questions');render()})}
function renderQuality(rows){const duplicateGroups=Object.entries(rows.filter(q=>q.duplicate_group).reduce((m,q)=>((m[q.duplicate_group]??=[]).push(q),m),{})).filter(([,v])=>v.length>1);const lowQuality=rows.filter(q=>!q.verified||completeness(q)<75||duplicateWeight(q)<1);$('#qualityStats').innerHTML=[['待审核',rows.filter(q=>!q.verified).length,'records'],['重复群组',duplicateGroups.length,'clusters'],['低完整度',rows.filter(q=>completeness(q)<75).length,'below 75%'],['来源链接',rows.filter(q=>q.source_url).length,'traceable']].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');const catalogRows=state.subject==='all'||state.subject==='Sejarah'?Object.entries(sejarahCatalog).flatMap(([form,chapters])=>chapters.map(chapter=>({form,chapter,items:questions.filter(q=>q.subject==='Sejarah'&&q.form===form&&q.chapter===chapter)}))):grouped(rows).map(g=>({form:g.form,chapter:g.chapter,items:g.items}));$('#coverageAudit').innerHTML=catalogRows.map(x=>{const years=new Set(x.items.map(q=>q.year)).size,verified=x.items.filter(q=>q.verified).length,coverage=Math.min(100,x.items.length*12+years*8+verified*5);return`<div class="audit-row"><div><strong>${safe(x.chapter)}</strong><small>${safe(x.form)} · ${x.items.length} 题 · ${years} 年份</small></div><div class="mini-meter"><i style="width:${coverage}%"></i></div><b>${coverage}%</b></div>`}).join('');$('#duplicateAudit').innerHTML=duplicateGroups.length?duplicateGroups.map(([id,items])=>`<div class="duplicate-card"><strong>${safe(id)}</strong><span>${items.length} 条记录 · 完整计分 1 条</span><small>${items.map(x=>safe(`${x.state||x.source}: ${x.question_id}`)).join('<br>')}</small></div>`).join(''):'<div class="empty">目前没有重复题群组</div>';$('#reviewQueue').innerHTML=lowQuality.sort((a,b)=>completeness(a)-completeness(b)).slice(0,12).map(q=>`<div class="review-item"><div><strong>${safe(q.question_id)} · ${safe(q.chapter)}</strong><span>${safe(q.source)} / ${safe(q.state||'州属未填')} / ${q.verified?'已验证':'待审核'}</span></div><div>${qualityLabel(q)}</div></div>`).join('')||'<div class="empty">当前筛选没有待处理记录</div>'}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row);return rows}
function normalizeRecord(obj,index){const bool=String(obj.verified).trim().toLowerCase();return enrichRecord({question_id:obj.question_id,year:Number(obj.year),subject:String(obj.subject||'').trim(),form:String(obj.form||'').trim(),source:String(obj.source||'').trim(),state:String(obj.state||'').trim(),paper:String(obj.paper||'').trim(),section:String(obj.section||'').trim(),question_no:String(obj.question_no||'').trim(),chapter:String(obj.chapter||'').trim(),topic:String(obj.topic||'').trim(),command_word:String(obj.command_word||'').trim(),cognitive:String(obj.cognitive||'').trim(),skills:String(obj.skills||'').trim(),type:String(obj.type||'').trim(),marks:Number(obj.marks),curriculum:String(obj.curriculum||'KSSM').trim(),verified:['true','1','yes','verified','已验证'].includes(bool),duplicate_group:String(obj.duplicate_group||'').trim(),source_url:String(obj.source_url||'').trim(),official:num(obj.official,.5),importance:num(obj.importance,50),gap:num(obj.gap,50),trial:num(obj.trial,50),fit:num(obj.fit,50),skill:num(obj.skill,50)},index)}
function recordKey(q){return [q.year,q.subject,q.form,q.source,q.state,q.paper,q.section,q.question_no,q.chapter,q.topic].map(x=>String(x).toLowerCase().trim()).join('|')}
$('#csvFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const result=$('#importResult');try{const matrix=parseCSV((await file.text()).replace(/^\uFEFF/,''));if(matrix.length<2)throw new Error('CSV 没有资料行');const headers=matrix[0].map(h=>h.trim());const required=['year','subject','form','source','paper','chapter','topic','type','marks','curriculum','verified'];const missing=required.filter(h=>!headers.includes(h));if(missing.length)throw new Error(`缺少字段：${missing.join(', ')}`);const existing=new Set(questions.map(recordKey));let added=0,duplicates=0,invalid=0,warnings=0;matrix.slice(1).forEach((values,index)=>{const raw=Object.fromEntries(headers.map((h,i)=>[h,values[i]??''])),q=normalizeRecord(raw,index);if(!q.year||!q.subject||!q.form||!q.source||!q.paper||!q.chapter||!q.topic||!q.type||!Number.isFinite(q.marks)){invalid++;return}if(q.subject==='Sejarah'&&sejarahCatalog[q.form]&&!sejarahCatalog[q.form].includes(q.chapter))warnings++;const key=recordKey(q);if(existing.has(key)){duplicates++;return}existing.add(key);imported.push(q);added++});saveImported();questions=[...seedQuestions,...imported].map(enrichRecord);refreshFilters();render();result.innerHTML=`<strong>导入完成</strong><br>新增 ${added} 条 · 完全重复 ${duplicates} 条 · 无效 ${invalid} 条 · 章节名称警告 ${warnings} 条`;result.className='import-result success'}catch(err){result.textContent=`导入失败：${err.message}`;result.className='import-result error'}finally{e.target.value=''}})
$('#clearImportedBtn').addEventListener('click',()=>{if(!confirm('确定清除这台浏览器导入的全部题目？'))return;imported=[];saveImported();questions=seedQuestions.map(enrichRecord);refreshFilters();render();$('#importResult').textContent='本机导入资料已清除。';$('#importResult').className='import-result muted'})
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
$('#exportBtn').addEventListener('click',()=>{const headers=['question_id','year','subject','form','source','state','paper','section','question_no','chapter','topic','command_word','cognitive','skills','type','marks','curriculum','verified','duplicate_group','source_url','official','importance','gap','trial','fit','skill'];const lines=[headers.join(','),...filtered().map(q=>headers.map(h=>csvEscape(q[h])).join(','))];const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='spm-question-export-v4.csv';a.click();URL.revokeObjectURL(a.href)})
function switchView(name){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(x=>x.classList.remove('active'));$(`#${name}View`)?.classList.add('active')}
['subject','form','chapter','year','paper','type','source'].forEach(k=>{$(`#${k}Filter`).addEventListener('change',e=>{state[k]=e.target.value;if(k==='subject'){state.form='all';state.chapter='all'}if(k==='form')state.chapter='all';refreshFilters();render()})});$('#verifyFilter').addEventListener('change',e=>{state.verify=e.target.value;render()});$('#searchInput').addEventListener('input',e=>{state.search=e.target.value.trim();render()});$('#resetBtn').addEventListener('click',()=>{Object.assign(state,{subject:'all',form:'all',chapter:'all',year:'all',paper:'all',type:'all',source:'all',verify:'all',search:''});refreshFilters();$$('.filters select').forEach(x=>x.value='all');$('#searchInput').value='';render()});$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view)));
refreshFilters();render();