const seedQuestions=[
{year:2025,subject:'Sejarah',source:'SPM',paper:'Paper 2',chapter:'Bab 8 Pilihan Raya',topic:'Proses pilihan raya',type:'Struktur',marks:6,curriculum:'KSSM',verified:true,official:1,importance:92,gap:70,trial:82,fit:88,skill:76},
{year:2024,subject:'Sejarah',source:'SPM',paper:'Paper 2',chapter:'Bab 10 Pemasyhuran Kemerdekaan',topic:'Kesan kemerdekaan',type:'Esei',marks:8,curriculum:'KSSM',verified:true,official:1,importance:96,gap:62,trial:74,fit:92,skill:84},
{year:2023,subject:'Sejarah',source:'SPM',paper:'Paper 1',chapter:'Bab 5 Persekutuan Tanah Melayu',topic:'Ciri persekutuan',type:'Objektif',marks:2,curriculum:'KSSM',verified:true,official:1,importance:86,gap:78,trial:65,fit:80,skill:70},
{year:2025,subject:'Sejarah',source:'Trial Negeri',paper:'Paper 2',chapter:'Bab 8 Pilihan Raya',topic:'Kepentingan pilihan raya',type:'Esei',marks:8,curriculum:'KSSM',verified:true,official:.6,importance:92,gap:70,trial:88,fit:91,skill:80},
{year:2024,subject:'Mathematics',source:'SPM',paper:'Paper 2',chapter:'Quadratic Functions',topic:'Graph and roots',type:'Structured',marks:6,curriculum:'KSSM',verified:true,official:1,importance:94,gap:65,trial:79,fit:92,skill:86},
{year:2023,subject:'Mathematics',source:'SPM',paper:'Paper 1',chapter:'Statistics',topic:'Measures of dispersion',type:'Objective',marks:3,curriculum:'KSSM',verified:true,official:1,importance:90,gap:72,trial:75,fit:88,skill:80},
{year:2022,subject:'Mathematics',source:'SPM',paper:'Paper 2',chapter:'Graphs of Motion',topic:'Distance-time graph',type:'Structured',marks:7,curriculum:'KSSM',verified:true,official:1,importance:92,gap:80,trial:83,fit:95,skill:88},
{year:2024,subject:'Science',source:'SPM',paper:'Paper 2',chapter:'Force and Motion',topic:'Experiment variables',type:'Structured',marks:8,curriculum:'KSSM',verified:true,official:1,importance:96,gap:68,trial:86,fit:96,skill:92},
{year:2023,subject:'Science',source:'SPM',paper:'Paper 2',chapter:'Electricity and Magnetism',topic:'Application of electromagnet',type:'Essay',marks:10,curriculum:'KSSM',verified:true,official:1,importance:91,gap:79,trial:82,fit:91,skill:84},
{year:2024,subject:'Bahasa Melayu',source:'SPM',paper:'Paper 1',chapter:'Karangan',topic:'Kesihatan dan gaya hidup',type:'Esei',marks:70,curriculum:'KSSM',verified:true,official:1,importance:95,gap:66,trial:80,fit:96,skill:90},
{year:2023,subject:'Bahasa Melayu',source:'SPM',paper:'Paper 2',chapter:'Sintaksis',topic:'Ayat aktif dan pasif',type:'Struktur',marks:6,curriculum:'KSSM',verified:true,official:1,importance:92,gap:76,trial:84,fit:94,skill:88},
{year:2024,subject:'English',source:'SPM',paper:'Paper 2',chapter:'Writing',topic:'Article / review',type:'Extended writing',marks:20,curriculum:'KSSM',verified:true,official:1,importance:94,gap:70,trial:81,fit:94,skill:91}
];
const STORAGE_KEY='spmqi_imported_v2';
let imported=loadImported();
let questions=[...seedQuestions,...imported];
const state={subject:'all',year:'all',paper:'all',source:'all',verify:'all',search:''};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function safe(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function loadImported(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
function saveImported(){localStorage.setItem(STORAGE_KEY,JSON.stringify(imported))}
function uniq(k){return [...new Set(questions.map(q=>q[k]).filter(v=>v!==''&&v!=null))].sort((a,b)=>typeof a==='number'?b-a:String(a).localeCompare(String(b)))}
function fill(id,values,allLabel){const el=$(id);const current=el.value;el.innerHTML=`<option value="all">${allLabel}</option>`+values.map(v=>`<option>${safe(v)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current}
function refreshFilters(){fill('#subjectFilter',uniq('subject'),'全部科目');fill('#yearFilter',uniq('year'),'全部年份');fill('#paperFilter',uniq('paper'),'全部 Paper');fill('#sourceFilter',uniq('source'),'全部来源')}
function filtered(){return questions.filter(q=>(state.subject==='all'||q.subject===state.subject)&&(state.year==='all'||String(q.year)===String(state.year))&&(state.paper==='all'||q.paper===state.paper)&&(state.source==='all'||q.source===state.source)&&(state.verify==='all'||(state.verify==='verified'?q.verified:!q.verified))&&(!state.search||`${q.chapter} ${q.topic} ${q.subject} ${q.source}`.toLowerCase().includes(state.search.toLowerCase())))}
function num(v,fallback=50){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):fallback}
function score(q){const age=Math.max(0,new Date().getFullYear()-Number(q.year));const recency=Math.max(25,100-age*9);const curriculumPenalty=String(q.curriculum).toUpperCase()==='KSSM'?0:18;const unverifiedPenalty=q.verified?0:8;const raw=25*(recency*num(q.official,0.5)/100)+20*num(q.importance)/100+15*num(q.gap)/100+15*num(q.trial)/100+10*num(q.fit)/100+10*num(q.skill)/100+5*(q.verified?1:.4)-curriculumPenalty-unverifiedPenalty;return Math.round(Math.max(0,Math.min(100,raw)))}
function grouped(rows){const map={};rows.forEach(q=>{const k=`${q.subject}||${q.chapter}`;(map[k]??=[]).push(q)});return Object.entries(map).map(([k,items])=>{const [subject,chapter]=k.split('||');return{subject,chapter,items,score:Math.round(items.reduce((s,q)=>s+score(q),0)/items.length),last:Math.max(...items.map(x=>Number(x.year))),marks:items.reduce((s,x)=>s+Number(x.marks||0),0),verified:items.filter(x=>x.verified).length/items.length}}).sort((a,b)=>b.score-a.score)}
function cls(n){return n>=80?'high':n>=65?'medium':n>=50?'normal':'low'}
function render(){const rows=filtered();const groups=grouped(rows);$('#stats').innerHTML=[['题目记录',rows.length,'当前筛选'],['涉及章节',groups.length,'自动归类'],['累计分数',rows.reduce((s,q)=>s+Number(q.marks||0),0),'marks'],['验证比例',rows.length?Math.round(rows.filter(q=>q.verified).length/rows.length*100)+'%':'0%','teacher checked']].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');renderHeat(groups);renderPriority(groups);renderBars(rows);renderTable(rows);renderPrediction(groups)}
function renderPriority(groups){$('#priorityList').innerHTML=groups.slice(0,6).map(g=>`<div class="priority-item"><div class="priority-top"><span class="priority-name">${safe(g.chapter)}<small>${safe(g.subject)}</small></span><strong class="score ${cls(g.score)}">${g.score}</strong></div><div class="meter"><i style="width:${g.score}%"></i></div><div class="reason">最近出现 ${g.last} · 累计 ${g.marks} 分 · ${g.items.length} 条记录</div></div>`).join('')||'<div class="empty">没有符合条件的数据</div>'}
function renderHeat(groups){const years=uniq('year').slice(0,6).sort();let html=`<div class="heat-row header"><span>章节</span>${years.map(y=>`<span>${y}</span>`).join('')}</div>`;groups.slice(0,8).forEach(g=>{html+=`<div class="heat-row"><span class="heat-label" title="${safe(g.chapter)}">${safe(g.chapter)}</span>${years.map(y=>{const value=g.items.filter(x=>String(x.year)===String(y)).reduce((s,x)=>s+Number(x.marks||0),0);const level=value===0?0:value<5?1:value<8?2:value<12?3:4;return`<span class="heat-cell heat-${level}">${value||'—'}</span>`}).join('')}</div>`});$('#heatmap').innerHTML=html||'<div class="empty">暂无数据</div>'}
function renderBars(rows){const years=uniq('year').sort();const values=years.map(y=>({y,v:rows.filter(q=>String(q.year)===String(y)).reduce((s,q)=>s+Number(q.marks||0),0)}));const max=Math.max(1,...values.map(x=>x.v));$('#bars').innerHTML=values.map(x=>`<div class="bar-group"><div class="bar" data-value="${x.v} marks" style="height:${Math.max(4,x.v/max*165)}px"></div><span>${x.y}</span></div>`).join('')}
function renderTable(rows){$('#resultCount').textContent=`${rows.length} records`;$('#questionTable').innerHTML=[...rows].sort((a,b)=>b.year-a.year).map(q=>`<tr><td>${q.year}</td><td><strong>${safe(q.subject)}</strong></td><td>${safe(q.source)}</td><td>${safe(q.paper)}</td><td><strong>${safe(q.chapter)}</strong><span class="muted">${safe(q.topic)}</span></td><td>${safe(q.type)}</td><td>${q.marks}</td><td>${safe(q.curriculum||'—')}</td><td class="${q.verified?'verified':'unverified'}">${q.verified?'已验证':'待审核'}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">没有符合条件的题目</td></tr>'}
function renderPrediction(groups){$('#predictionBoard').innerHTML=groups.map(g=>{const conf=Math.round(g.verified*100*Math.min(1,g.items.length/3));const reason=g.score>=80?'信号强，但仍须完成来源核对与完整题型训练。':g.score>=65?'具有明显复习价值，建议掌握核心概念与常见题型。':'维持基础覆盖，不建议完全忽略。';return`<div class="prediction-item"><div><h3>${safe(g.chapter)}</h3><div class="prediction-meta"><span>${safe(g.subject)}</span><span>最近 ${g.last}</span><span>${g.items.length} 条记录</span><span>${g.marks} marks</span></div><p class="reason">${reason}</p></div><div class="prediction-score"><strong class="score ${cls(g.score)}">${g.score}</strong><span class="confidence">置信度 ${conf}%</span></div></div>`}).join('')||'<div class="empty">暂无预测结果</div>'}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row);return rows}
function normalizeRecord(obj){const bool=String(obj.verified).trim().toLowerCase();return{year:Number(obj.year),subject:String(obj.subject||'').trim(),source:String(obj.source||'').trim(),paper:String(obj.paper||'').trim(),chapter:String(obj.chapter||'').trim(),topic:String(obj.topic||'').trim(),type:String(obj.type||'').trim(),marks:Number(obj.marks),curriculum:String(obj.curriculum||'KSSM').trim(),verified:['true','1','yes','verified','已验证'].includes(bool),official:num(obj.official,.5),importance:num(obj.importance,50),gap:num(obj.gap,50),trial:num(obj.trial,50),fit:num(obj.fit,50),skill:num(obj.skill,50)}}
function recordKey(q){return [q.year,q.subject,q.source,q.paper,q.chapter,q.topic,q.type].map(x=>String(x).toLowerCase().trim()).join('|')}
$('#csvFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const result=$('#importResult');try{const matrix=parseCSV((await file.text()).replace(/^\uFEFF/,''));if(matrix.length<2)throw new Error('CSV 没有资料行');const headers=matrix[0].map(h=>h.trim());const required=['year','subject','source','paper','chapter','topic','type','marks','curriculum','verified'];const missing=required.filter(h=>!headers.includes(h));if(missing.length)throw new Error(`缺少字段：${missing.join(', ')}`);const existing=new Set(questions.map(recordKey));let added=0,duplicates=0,invalid=0;matrix.slice(1).forEach(values=>{const raw=Object.fromEntries(headers.map((h,i)=>[h,values[i]??'']));const q=normalizeRecord(raw);if(!q.year||!q.subject||!q.source||!q.paper||!q.chapter||!q.topic||!q.type||!Number.isFinite(q.marks)){invalid++;return}const key=recordKey(q);if(existing.has(key)){duplicates++;return}existing.add(key);imported.push(q);added++});saveImported();questions=[...seedQuestions,...imported];refreshFilters();render();result.innerHTML=`<strong>导入完成</strong><br>新增 ${added} 条 · 重复跳过 ${duplicates} 条 · 无效 ${invalid} 条`;result.className='import-result success'}catch(err){result.textContent=`导入失败：${err.message}`;result.className='import-result error'}finally{e.target.value=''}})
$('#clearImportedBtn').addEventListener('click',()=>{if(!confirm('确定清除这台浏览器导入的全部题目？'))return;imported=[];saveImported();questions=[...seedQuestions];refreshFilters();render();$('#importResult').textContent='本机导入资料已清除。';$('#importResult').className='import-result muted'})
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
$('#exportBtn').addEventListener('click',()=>{const headers=['year','subject','source','paper','chapter','topic','type','marks','curriculum','verified','official','importance','gap','trial','fit','skill'];const lines=[headers.join(','),...filtered().map(q=>headers.map(h=>csvEscape(q[h])).join(','))];const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='spm-question-export.csv';a.click();URL.revokeObjectURL(a.href)})
['subject','year','paper','source','verify'].forEach(k=>{$(`#${k}Filter`).addEventListener('change',e=>{state[k]=e.target.value;render()})});$('#searchInput').addEventListener('input',e=>{state.search=e.target.value.trim();render()});$('#resetBtn').addEventListener('click',()=>{Object.assign(state,{subject:'all',year:'all',paper:'all',source:'all',verify:'all',search:''});$$('.filters select').forEach(x=>x.value='all');$('#searchInput').value='';render()});$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#${btn.dataset.view}View`).classList.add('active')}));refreshFilters();render();